version: '3.7'

services:
  lanchonete:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/src
    working_dir: /app/src
    depends_on:
      - mongo
    environment:
      - MONGODB_HOST=mongo:27017
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_DATABASE=lanchonete
    networks:
      - default

  mongo:
    container_name: mongo-lanchonete
    image: 'bitnami/mongodb:4.4'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_lanchonete_data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=lanchonete

    networks:
      - default

volumes:
  mongodb_lanchonete_data:
    driver: local

networks:
  default:
    name: lanchonete_network